logging:
  level:
    #ROOT: DEBUG
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: c:/apps/debug.log