package com.cast.demo.mapper;

import com.cast.demo.pojo.Actor;
import com.cast.demo.pojo.ActorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int countByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int deleteByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int deleteByPrimaryKey(Short actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int insertSelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    List<Actor> selectByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    Actor selectByPrimaryKey(Short actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int updateByExample(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated Mon Dec 18 13:56:49 CST 2017
     */
    int updateByPrimaryKey(Actor record);
}